name: Sequential Jobs Example

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Running Job 1"

  job2:
    needs: job1  # Waits for job1 to finish
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: echo "Running Job 2"

  job3:
    needs: job2  # Waits for job2 to finish
    runs-on: ubuntu-latest
    steps:
      - name: Step 3
        run: echo "Running Job 3"
