name: Launch EC2 Instance

on:
  workflow_dispatch:  # Manual trigger

jobs:
  launch-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Launch EC2 Instance
        run: |
          aws ec2 run-instances \
            --image-id ami-0861f4e788f5069dd \                # Replace with valid AMI
            --count 1 \
            --instance-type t2.micro \
            --key-name my-key \                          # Replace with your key pair
            --security-groups default \                       # Or use a security group ID
