name: Launch EC2 Instance

on:
  workflow_dispatch:

jobs:
  launch-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Launch EC2 Instance
        run: |
          set -x
          aws ec2 run-instances \
            --image-id ami-0861f4e788f5069dd \
            --count 1 \
            --instance-type t2.micro \
            --key-name my-key-pair \
            --security-group-ids sg-07d5b72f49350b93f \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=GitHubLaunched}]'
